// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "stringer -output=string.go -type=ChassisIDSubtype,PortIDSubtype"; DO NOT EDIT.

package lldp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChassisIDSubtypeReserved-0]
	_ = x[ChassisIDSubtypeChassisComponent-1]
	_ = x[ChassisIDSubtypeInterfaceAlias-2]
	_ = x[ChassisIDSubtypePortComponent-3]
	_ = x[ChassisIDSubtypeMACAddress-4]
	_ = x[ChassisIDSubtypeNetworkAddress-5]
	_ = x[ChassisIDSubtypeInterfaceName-6]
	_ = x[ChassisIDSubtypeLocallyAssigned-7]
}

const _ChassisIDSubtype_name = "ChassisIDSubtypeReservedChassisIDSubtypeChassisComponentChassisIDSubtypeInterfaceAliasChassisIDSubtypePortComponentChassisIDSubtypeMACAddressChassisIDSubtypeNetworkAddressChassisIDSubtypeInterfaceNameChassisIDSubtypeLocallyAssigned"

var _ChassisIDSubtype_index = [...]uint8{0, 24, 56, 86, 115, 141, 171, 200, 231}

func (i ChassisIDSubtype) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ChassisIDSubtype_index)-1 {
		return "ChassisIDSubtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChassisIDSubtype_name[_ChassisIDSubtype_index[idx]:_ChassisIDSubtype_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PortIDSubtypeReserved-0]
	_ = x[PortIDSubtypeInterfaceAlias-1]
	_ = x[PortIDSubtypePortComponent-2]
	_ = x[PortIDSubtypeMACAddress-3]
	_ = x[PortIDSubtypeNetworkAddress-4]
	_ = x[PortIDSubtypeInterfaceName-5]
	_ = x[PortIDSubtypeAgentCircuitID-6]
	_ = x[PortIDSubtypeLocallyAssigned-7]
}

const _PortIDSubtype_name = "PortIDSubtypeReservedPortIDSubtypeInterfaceAliasPortIDSubtypePortComponentPortIDSubtypeMACAddressPortIDSubtypeNetworkAddressPortIDSubtypeInterfaceNamePortIDSubtypeAgentCircuitIDPortIDSubtypeLocallyAssigned"

var _PortIDSubtype_index = [...]uint8{0, 21, 48, 74, 97, 124, 150, 177, 205}

func (i PortIDSubtype) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PortIDSubtype_index)-1 {
		return "PortIDSubtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PortIDSubtype_name[_PortIDSubtype_index[idx]:_PortIDSubtype_index[idx+1]]
}
